services:
  gp-verify-bot:
    build:
      context: .
      network: host

    container_name: gp-verify-bot
    restart: unless-stopped
    network_mode: host

    working_dir: /code

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code

    dns:
      - 100.127.255.1

    dns_opt:
      - timeout:2
      - attempts:2

    volumes:
      - ./app:/code/app
      - ./data:/data
      - ./logs:/logs

    command: ["python", "-m", "app.main"]

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"